- app/controllers/docs_controller.rb
- app/javascript/controllers/alert_dialog_controller.js
- app/javascript/controllers/dismissable_controller.js
- app/javascript/controllers/index.js
- app/views/components/alert_dialog.rb
- app/views/components/alert_dialog_action.rb
- app/views/components/alert_dialog_cancel.rb
- app/views/components/alert_dialog_content.rb
- app/views/components/alert_dialog_description.rb
- app/views/components/alert_dialog_footer.rb
- app/views/components/alert_dialog_header.rb
- app/views/components/alert_dialog_title.rb
- app/views/components/alert_dialog_trigger.rb
- app/views/components/button.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/alert_dialog_view.rb
- config/routes.rb
Alert Dialog
Demo:
https://github.com/georgekettle/phlex-components-library/assets/34521157/a8eb6369-e65e-4379-997b-36cbe075dd1c
> Alert dialog

- app/controllers/docs_controller.rb
- app/javascript/controllers/index.js
- app/views/components/aspect_ratio.rb
- app/views/components/shared/navbar.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/aspect_ratio_view.rb
- config/routes.rb
AspectRatio
Demo:
https://github.com/georgekettle/phlex-components-library/assets/34521157/9ab25f96-4b5d-4f26-a0e8-135e8a9a1933
> Created AspectRatio component

- Gemfile.lock
- app/javascript/controllers/index.js
- config/environments/production.rb
- Added config.force_ssl = true
> Force https

- app/controllers/docs_controller.rb
- app/views/components/card.rb
- app/views/components/card_content.rb
- app/views/components/card_description.rb
- app/views/components/card_footer.rb
- app/views/components/card_header.rb
- app/views/components/card_title.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/card_view.rb
- config/routes.rb
> Card compoenent

- app/controllers/docs_controller.rb
- app/javascript/controllers/dialog_controller.js
- app/javascript/controllers/index.js
- app/views/components/alert_dialog_trigger.rb
- app/views/components/dialog.rb
- app/views/components/dialog_content.rb
- app/views/components/dialog_description.rb
- app/views/components/dialog_footer.rb
- app/views/components/dialog_header.rb
- app/views/components/dialog_middle.rb
- app/views/components/dialog_title.rb
- app/views/components/dialog_trigger.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/dialog_view.rb
- config/routes.rb
Dialog
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/748bbd85-0a6b-4fbf-bc8c-00ace8e6053e
> Dialog component created

- app/controllers/docs_controller.rb
- app/views/components/checkbox.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/checkbox_view.rb
- config/routes.rb
> Checkbox component

- app/controllers/docs_controller.rb
- app/javascript/controllers/collapsible_controller.js
- app/javascript/controllers/index.js
- app/views/components/collapsible.rb
- app/views/components/collapsible_content.rb
- app/views/components/collapsible_trigger.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/collapsible_view.rb
- config/routes.rb
Collapsible
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/06a33540-f845-4955-8d52-80abc361f97e
> Collapsible

- app/controllers/docs_controller.rb
- app/javascript/controllers/calendar_controller.js
- app/javascript/controllers/index.js
- app/views/components/calendar.rb
- app/views/components/shared/sidebar.rb
- app/views/components/typography/p.rb
- app/views/docs/calendar_view.rb
- config/routes.rb
- package.json
- yarn.lock
Calendar (WIP)
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/19f7c569-160e-4e5d-9c36-2c4b6833e2aa
> Calendar (WIP)

- app/views/components/link.rb
- app/views/components/shared/logo.rb
- app/views/components/shared/menu.rb
- app/views/components/shared/mobile_menu.rb
- app/views/components/shared/navbar.rb
- app/views/components/shared/sidebar.rb
- app/views/docs/sheet_view.rb
Mobile Menu
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/53557e1d-b71d-4ade-949f-bf77ac38eaee
> Mobile menu

- app/controllers/docs_controller.rb
- app/views/components/shared/menu.rb
- app/views/docs/date_picker_view.rb
- config/routes.rb
DatePicker Component created with Calendar and Popover
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/2399fafd-3e37-4660-b2b3-671e648f1781
> DatePicker component

- app/controllers/docs_controller.rb
- app/javascript/controllers/popover_controller.js
- app/views/components/dropdown_menu.rb
- app/views/components/dropdown_menu_content.rb
- app/views/components/dropdown_menu_item.rb
- app/views/components/dropdown_menu_label.rb
- app/views/components/dropdown_menu_separator.rb
- app/views/components/dropdown_menu_trigger.rb
- app/views/components/shared/menu.rb
- app/views/docs/dropdown_menu_view.rb
- app/views/docs/popover_view.rb
- config/routes.rb
DropdownMenu component
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/d381e07f-5d7c-49e9-b6a9-04f9285950b8
> DropdownMenu component

- app/controllers/docs_controller.rb
- app/views/components/hover_card.rb
- app/views/components/hover_card_content.rb
- app/views/components/hover_card_trigger.rb
- app/views/components/shared/menu.rb
- app/views/docs/hover_card_view.rb
- config/routes.rb
HoverCard component
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/4bd3ae40-d0a9-4e1a-ba8f-dd2d706fc3e8
> HoverCard component

- app/controllers/docs_controller.rb
- app/views/components/docs/visual_code_example.rb
- app/views/components/shared/menu.rb
- app/views/components/tooltip.rb
- app/views/components/tooltip_content.rb
- app/views/components/tooltip_trigger.rb
- app/views/docs/tooltip_view.rb
- config/routes.rb
Tooltip component
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/7253449a-2755-4a5a-b18e-d25943afdbfd
> Tooltip component

- app/controllers/docs_controller.rb
- app/javascript/controllers/popover_controller.js
- app/views/components/context_menu.rb
- app/views/components/context_menu_content.rb
- app/views/components/context_menu_item.rb
- app/views/components/context_menu_label.rb
- app/views/components/context_menu_separator.rb
- app/views/components/context_menu_trigger.rb
- app/views/components/dropdown_menu_item.rb
- app/views/components/shared/menu.rb
- app/views/docs/command_view.rb
- app/views/docs/context_menu_view.rb
- config/routes.rb
ContextMenu components
Demo:
https://github.com/georgekettle/PhlexUI/assets/34521157/a96236e0-dcca-4fcb-a4e2-1f636d5616e2
> Context menu

- Gemfile
- Gemfile.lock
- app/views/docs/installation/rails_bundler_view.rb
- app/views/docs/installation/rails_importmaps_view.rb
- tailwind.config.js
- yarn.lock
- Removed all references of gem fury source
- Updated installation instructions to reflect changes
> Remove gem source

- .github/workflows/main.yml
After that PR, all PRs should target v1
> Deploying v1 on fly.io

- Gemfile
- Gemfile.lock
- app/controllers/docs_controller.rb
- app/javascript/application.js
- app/views/application_view.rb
- app/views/components/docs/components_table.rb
- app/views/docs/combobox_view.rb
- config/routes.rb
- package.json
- yarn.lock
this adds the combobox component and rbui gem and js package v1 alpha. 
This PR can be used as a reference on how to add the js to the phlex_ui / rbui mono-repo.
also add all available components and js controllers
> add combobox and rbui v1

- .github/workflows/main.yml
> Adding v1 as trigger to CI

- app/views/components/shared/menu.rb
- Adding Combobox
- Remove coming soon (no promises here)
- Remove premium status
> Adding Combobox to component menu

- Gemfile.lock
- app/views/components/shared/navbar.rb
- app/views/components/test_view.rb
- app/views/docs/theme_toggle_view.rb
- yarn.lock
> Migrate theme toggle to RBUI

- Gemfile.lock
- test/components/previews/rbui/table_preview.rb
- yarn.lock
https://github.com/PhlexUI/phlex_ui/pull/92
> Migrate table

- app/views/docs/accordion_view.rb
- test/components/previews/rbui/accordion_preview.rb
> Adjust accordion to use RBUI and default look and feel

- app/views/docs/accordion_view.rb
@cirdes were you talking about this? Or do you want to change code format to use 2 spaces instead tabs?
> Fix accordion code indent

- Gemfile.lock
- yarn.lock
Just upgrade RubyUI to get new Codeblock indentation/tabsize
> Upgrade RubyUI

- app/views/docs/installation/rails_bundler_view.rb
Update setup instructions to use our generator or the manual setup. Please, leave suggestions on how to improve the texts or fixing errors on review or open new PRs with the improvements.
> Update setup instructions for Rails + JS bundler

- Gemfile.lock
- app/components/ruby_ui/combobox/combobox_toggle_all_checkbox.rb
- app/javascript/controllers/ruby_ui/combobox_controller.js
- app/views/docs/combobox_view.rb
- package.json
- yarn.lock
Add an example demonstrating how to use a "toggle all" checkbox to select or deselect all options in a combobox. 
Here's a quick demo:
https://github.com/user-attachments/assets/53b74824-4a0f-4015-85da-5e66bf92b5d7
> Add toggle all example to combobox docs

- app/views/docs/installation/rails_bundler.rb
- app/views/docs/installation/rails_importmaps.rb
Update installation instructions following recent RubyUI changes to work with Tailwind V4.
> Update installation instructions for Tailwind V4

- Gemfile.lock
- app/components/shared/menu.rb
- app/controllers/docs_controller.rb
- app/views/docs/separator.rb
- config/routes.rb
Add the separator component to the docs:
> Add the separator component

- .github/workflows/deploy.yml
- .github/workflows/main.yml
Update GitHub Actions configuration by:
1. Renaming fly-deploy.yml to deploy.yml
2. Changing deploy workflow to manual trigger (workflow_dispatch)
3. Updating CI workflow configuration
> Refactor GitHub Actions workflows

- app/components/ruby_ui/tabs/tabs_trigger.rb
- app/views/docs/tabs.rb
> aria-disabled for Tabs
