ruby-ui/web

.github/workflows/main.yml, Gemfile, bin/dev
This PR introduces several improvements to our development and deployment workflow:
1. Integrates Overmind into bin/dev for better process management
2. Implements Heroku deployment capabilities
3. Cleans up and optimizes our Gemfile
- Added Overmind to bin/dev script
- Updated development workflow to utilize Overmind for process management
- Set up necessary configurations for Heroku deployment
- Changed the way we reference the github repo for the `phlex_ui` gem.
=> Add Overmind to bin/dev, implement Heroku deploy, and clean up Gemfile

Gemfile.lock, test/components/previews/rbui/aspect_ratio_preview.rb, test/components/previews/rbui/badge_preview.rb, test/components/previews/rbui/button_preview.rb, test/components/previews/rbui/codeblock_preview.rb, test/components/previews/rbui/link_preview.rb, test/components/previews/rbui/shortcut_key_preview.rb, yarn.lock
https://github.com/PhlexUI/phlex_ui/pull/93
- AspectRatio
- Badge
- Button
- Codeblock
- Link
- Shortcut
=> Migrate standalone components

Gemfile.lock, README.md, app/controllers/docs_controller.rb, app/views/components/shared/menu.rb, app/views/docs/textarea_view.rb, config/routes.rb, test/components/previews/rbui/textarea_preview.rb
The error will be fixed when RBUI merges the Textarea PR
=> ADD TEXTAREA

Gemfile.lock, app/controllers/docs_controller.rb, app/views/components/shared/menu.rb, app/views/docs/masked_input_view.rb, config/routes.rb, yarn.lock
This PR depends of https://github.com/ruby-ui/ruby_ui/pull/189. We need to update ruby_ui gem and js package before merging this PR.
=> Add MaskedInput component

app/javascript/controllers/index.js, app/javascript/controllers/sidebar_menu_controller.js, app/views/components/shared/sidebar.rb, package.json, yarn.lock
At first I thought it was a problem with turbo, but I think there is an incompatibility with sticky/overflow/fixed styles. I tried using `data_turbo_action: "replace"` on menu links to work with morph/preserve turbo options, but it didn't work. The solution I found was storing scroll position on localstorage before leaving page and get scroll position after visit.
Before:
https://github.com/user-attachments/assets/03451e11-96b3-4c6d-bfbe-1a47e736aaf8
After:
https://github.com/user-attachments/assets/afd0a4ce-9f3b-4689-85de-826f00896595
=> Fix menu scroll position

app/views/docs/installation/rails_bundler_view.rb, app/views/docs/installation/rails_importmaps_view.rb
Add updated instructions to importmap installation doc page. In the future we can extract some shared sections between jsbundling page and importmaps page and reuse them.
=> Update importmap setup instructions

app/components/component_setup/cli_steps.rb, app/components/component_setup/manual_steps.rb, app/components/component_setup/tabs.rb, app/lib/ruby_ui/file_manager.rb
Add manual steps for component installation. I tried to make it generic using code from RubyUI files and dependencies.yml.
Result:
=> Add manual component installation instructions

Gemfile.lock, app/components/ruby_ui/breadcrumb.rb, app/components/ruby_ui/breadcrumb/breadcrumb_ellipsis.rb, app/components/ruby_ui/breadcrumb/breadcrumb_item.rb, app/components/ruby_ui/breadcrumb/breadcrumb_link.rb, app/components/ruby_ui/breadcrumb/breadcrumb_list.rb, app/components/ruby_ui/breadcrumb/breadcrumb_page.rb, app/components/ruby_ui/breadcrumb/breadcrumb_separator.rb, app/controllers/docs_controller.rb, app/views/components/shared/menu.rb, app/views/docs/breadcrumb_view.rb, config/routes.rb
I implemented the Breadcrumb component based on the `shadcn/ui` library and used their official documentation as a reference to create usage examples. The component documentation includes the following sections:
=> Add breadcrumb to the documentation

Gemfile.lock, app/components/ruby_ui/alert.rb, app/components/ruby_ui/alert_dialog/alert_dialog_footer.rb, app/components/ruby_ui/alert_dialog/alert_dialog_header.rb, app/components/ruby_ui/dialog/dialog_content.rb, app/components/ruby_ui/dialog/dialog_footer.rb, app/components/ruby_ui/dialog/dialog_header.rb, app/components/ruby_ui/sheet/sheet_content.rb
Update components to get RTL support: https://github.com/ruby-ui/ruby_ui/pull/206
=> Update alert, alert dialog, dialog and sheet components from RubyUI

app/components/ruby_ui/radio_button.rb, app/controllers/docs_controller.rb, app/views/components/shared/menu.rb, app/views/docs/radio_button_view.rb, config/routes.rb
Issue #152 
Add the RadioButton component to the docs:
=> Add the radio button component to the docs

app/components/ruby_ui/skeleton.rb, app/controllers/docs_controller.rb, app/views/components/shared/menu.rb, app/views/docs/skeleton_view.rb, config/routes.rb
This PR adds the Skeleton component to the docs:
=> Add Skeleton component to the docs

Gemfile.lock, app/components/component_setup/tabs.rb
I upgraded the Phlex gem to version 2.0.2, but during the process, the tests started failing with the error:
> missing keyword "component_name"
This occurred when rendering the Tabs component. 
After some investigation, I discovered that the internal Tabs component used within the main component requires the RubyUI module to be explicitly specified.
=> Upgrade phlex and phlex-rails to 2.0.2 version

app/javascript/controllers/sidebar_menu_controller.js, app/views/components/shared/head.rb
There is a glitch occurring during navigation between components. Whenever you hover over a link to another component page, the following error is rendered:
`Uncaught (in promise) TypeError: map3.get is not a function`
After some research, I found that [changing the type attribute of the javascript_include_tag from `defer` to `module`](https://gist.github.com/pch/fe276b29ba037bdaeaa525932478ca18) resolves this issue. While this eliminates the error, the glitch persisted.
After further exploration, I followed [Konnor Rogers's approach](https://dev.to/konnorrogers/maintain-scroll-position-in-turbo-without-data-turbo-permanent-2b1i) and updated the Turbo events used in the controller. Now, the navigation is smooth without any glitches. Here's a demo: …
=> fix Glitch in the sidebar during navigation

app/components/base.rb, app/views/components/shared/logo.rb, app/views/components/shared/menu.rb, app/views/components/shared/navbar.rb, app/views/docs/aspect_ratio_view.rb, app/views/docs/card_view.rb, app/views/docs/command_view.rb, app/views/docs/dialog_view.rb, app/views/docs/getting_started/installation_view.rb, app/views/docs/typography_view.rb, app/views/errors/internal_server_error_view.rb, app/views/errors/not_found_view.rb, app/views/layouts/application_layout.rb, app/views/layouts/docs_layout.rb, app/views/layouts/errors_layout.rb, app/views/layouts/mailer_layout.rb, app/views/layouts/pages_layout.rb, app/views/pages/home_view.rb, app/views/themes/customize_popover.rb, app/views/themes/grid/card.rb, app/views/themes/grid/command.rb
We received the following warning from Phlex:
```
The `helpers` method is deprecated and will be removed in the next
minor version of phlex-rails.
If you absolutely need to access the underlying Rails view context,
you can do that via the `view_context` method, though this is
not recommended.
It is much safer to use one of the built-in helper adapters or to
register your own adapter via `register_output_helper` or
`register_value_helper`.
See https://beta.phlex.fun/rails/helpers.html
```
To address this, I have adapted the code to be compatible with the next version, ensuring we follow the recommended practices and avoid future issues with the deprecation of the `helpers` method.
=> Remove 'helpers' prefix

Gemfile.lock, app/components/ruby_ui/carousel.rb, app/components/ruby_ui/carousel/carousel_content.rb, app/components/ruby_ui/carousel/carousel_item.rb, app/components/ruby_ui/carousel/carousel_next.rb, app/components/ruby_ui/carousel/carousel_previous.rb, app/components/shared/menu.rb, app/controllers/docs_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/ruby_ui/carousel_controller.js, app/views/docs/carousel.rb, config/routes.rb, package.json, yarn.lock
This PR adds the Carousel component to the docs:
=> Add Carousel component

app/assets/stylesheets/application.tailwind.css, app/components/component_setup/manual_steps.rb, app/lib/ruby_ui/file_manager.rb, app/views/docs/installation/rails_bundler.rb, app/views/docs/installation/rails_importmaps.rb, package.json, yarn.lock
Related: https://github.com/ruby-ui/ruby_ui/pull/238
=> Update manual instructions to install components

app/components/ruby_ui/base.rb, app/components/ruby_ui/theme_toggle/set_dark_mode.rb, app/components/ruby_ui/theme_toggle/set_light_mode.rb, app/components/ruby_ui/theme_toggle/theme_toggle.rb, app/components/shared/navbar.rb, app/views/docs/getting_started/dark_mode.rb, app/views/docs/theme_toggle.rb
https://github.com/ruby-ui/ruby_ui/pull/258
=> split theme components from slot to components

.github/workflows/main.yml
This PR updates our GitHub Actions workflows to use devcontainers instead of directly setting up the environment on the runner. This approach:
- Ensures CI runs in the same environment as development
- Simplifies workflow configuration
- Reduces maintenance by centralizing environment setup in the devcontainer
- Increases CI timeout to accommodate container build time
We now have 1 ci step instead of 3, and the ci will cache the Docker image to speed up future builds. Now we can ensure that devcontainers will not be broken.
=> Use devcontainers for CI workflows

app/views/pages/home.rb
This PR adds a YouTube demo video to the homepage and updates the performance metrics to reflect the latest benchmarks (7.7x faster than ERB) with a link to the benchmark source.
=> Add demo video and update performance metrics

app/components/ruby_ui/link/link.rb, app/views/docs/link.rb
@cirdes @stephannv
the pure `disabled` never worked for Link because the tag `a` does not accept `disabled`.
but `aria-disabled` is working pretty well.
should we accept `disabled` here?
=> aria-disabled for Link

Gemfile.lock, app/components/ruby_ui/combobox/combobox_checkbox.rb, app/components/ruby_ui/combobox/combobox_radio.rb, app/components/ruby_ui/combobox/combobox_search_input.rb, app/components/ruby_ui/combobox/combobox_toggle_all_checkbox.rb, app/components/ruby_ui/combobox/combobox_trigger.rb, app/javascript/controllers/ruby_ui/combobox_controller.js, app/views/docs/combobox.rb
=> disabled + aria-disabled examples for Combobox

app/components/ruby_ui/select/select_item.rb, app/components/ruby_ui/select/select_trigger.rb, app/views/docs/select.rb
=> aria-disabled for Select

app/components/ruby_ui/form/form_field_label.rb, app/components/ruby_ui/radio_button/radio_button.rb, app/views/docs/radio_button.rb
@cirdes @stephannv it is necessary to add `class: "peer"` in RadioButton to apply the `disable` styles in the FormFieldLabel... I guess we should fix it in the `ruby_ui` gem.
=> aria-disabled for RadioButton

app/components/ruby_ui/switch/switch.rb, app/views/docs/switch.rb
=> aria-disabled for Switch

app/components/ruby_ui/textarea/textarea.rb, app/views/docs/textarea.rb
=> aria-disabled for Textarea

app/views/docs/date_picker.rb
This PR aims to resolve issue https://github.com/ruby-ui/web/issues/149.
I noticed that there is no Stimulus controller named simply input, but rather ruby-ui--calendar-input.
Additionally, in [method](https://github.com/ruby-ui/ruby_ui/blob/f5a275f191c32bd50d8ab2876a32586cf9435866/lib/ruby_ui/popover/popover_controller.js#L37), there is no trigger for focusin, only for hover and click. In this PR, I set it to click.
=> fix: datepicker not opening
